In [3]:
import os
PROJ_ROOT = os.path.abspath(os.path.join(os.pardir))
print(PROJ_ROOT)

/home/bruno/Desktop/coarse-discourse-validation

In [32]:
import pandas as pd
import json

In [54]:
filepath = os.path.join(PROJ_ROOT, 'data', 'raw', 'coarse_discourse_dump_reddit.json')

df = pd.read_json(filepath, lines=True) # 'lines' so pandas reads each line of file as a json object

df.head()

,is_self_post,posts,subreddit,title,url
0,1.0,"[{'id': 't3_1bx6qw', 'annotations': [{'link_to...",100movies365days,DTX120: #87 - Nashville,https://www.reddit.com/r/100movies365days/comm...
1,1.0,"[{'id': 't3_omv7p', 'annotations': [{'link_to_...",100sets,"Male, 23 years old. Going for 100 sets!",https://www.reddit.com/r/100sets/comments/omv7...
2,1.0,"[{'id': 't3_259tbh', 'annotations': [{'link_to...",1200isplenty,122cal black currant cheesecake!,https://www.reddit.com/r/1200isplenty/comments...
3,1.0,"[{'id': 't3_16h61h', 'annotations': [{'link_to...",1911,Need help finding a Springfield!,https://www.reddit.com/r/1911/comments/16h61h/...
4,1.0,"[{'id': 't3_35igzp', 'annotations': [{'link_to...",1911,Help with a possible trade?,https://www.reddit.com/r/1911/comments/35igzp/...

In [53]:
# Brute Dataframe size
len(df)

9483

In [20]:
# Converts 'is_self_post' column to boolean
df['is_self_post'] = df['is_self_post'].fillna(0).astype('bool')

df[df['is_self_post']!= True].head()

,is_self_post,posts,subreddit,title,url
13,False,"[{'id': 't3_2kmipp', 'is_first_post': True, 'm...",2007scape,My best elite so far - double afros...,https://www.reddit.com/r/2007scape/comments/2k...
24,False,"[{'id': 't3_3j07o7', 'is_first_post': True, 'm...",2007scape,Would this be considered 1:1 input?,https://www.reddit.com/r/2007scape/comments/3j...
49,False,"[{'id': 't3_4hpmtj', 'is_first_post': True, 'm...",3dprinting,"Printed a computer mouse in ProMatte, sanded a...",https://www.reddit.com/r/3Dprinting/comments/4...
70,False,"[{'id': 't3_3w7d1j', 'is_first_post': True, 'm...",afl,Clem Smith forced to apologise to Blues after ...,https://www.reddit.com/r/AFL/comments/3w7d1j/c...
82,False,"[{'id': 't3_43nuh6', 'is_first_post': True, 'm...",actionfigures,Sunnydale Library... Or Xavirer's School for g...,https://www.reddit.com/r/ActionFigures/comment...

In [50]:
# Verifies structures of posts inside thread example
dposts = pd.DataFrame(df.iloc[1]['posts'])

dposts.head()

,annotations,author,body,id,in_reply_to,is_first_post,majority_link,majority_type,post_depth,url
0,"[{'link_to_post': 'none', 'main_type': 'announ...",Keatonus,"Alright guys, little background about myself. ...",t3_omv7p,NaN,True,none,announcement,NaN,https://www.reddit.com/r/100sets/comments/omv7...
1,"[{'link_to_post': 't3_omv7p', 'main_type': 'el...",Keatonus,**January 16th 3 Sets:** \nWent out shopping w...,t1_c3igqif,t3_omv7p,NaN,t3_omv7p,elaboration,1.0,NaN
2,"[{'link_to_post': 't1_c3igqif', 'main_type': '...",NaN,NaN,t1_c3imrkb,t1_c3igqif,NaN,t1_c3igqif,humor,2.0,NaN
3,"[{'link_to_post': 't3_omv7p', 'main_type': 'ap...",answerorreply,"dude, these sets are awesome. You're doing gre...",t1_c3ij8z0,t3_omv7p,NaN,t3_omv7p,appreciation,1.0,NaN
4,"[{'link_to_post': 't1_c3ij8z0', 'main_type': '...",Keatonus,"Thanks man! Yeah I'm trying to just keep the ""...",t1_c3inx9t,t1_c3ij8z0,NaN,t1_c3ij8z0,appreciation,2.0,NaN

In [52]:
# Total amount of posts analyzed
total_len = 0
for i in range(0, len(df)):
    total_len += len(df.iloc[i]['posts'])

total_len

116357